### ISSUE TITLE
Ano no canto superior esquerdo

### ISSUE THREAD

**Issue by Hugainz** [cesium/2016.seium.org#12]
No canto superior esquerdo, no elemento que aparece quando se faz hover sobre o logo da SEI, aparece 2016 em vez de 2017.
![screenshot from 2017-01-12 14-37-24](https://cloud.githubusercontent.com/assets/17356700/21893887/e9438274-d8d4-11e6-9180-bec2afa67bcb.png)

**Comment by joaofcosta** [comment]
@Hugainz Repositório errado hahaha
Mas obrigado! Se quiseres abre no outro repo um issue só para não ficar esquecido ;)

**Comment by Hugainz** [comment]
my bad :|
